
services:
 
  php8:
    build: .
    container_name: app_projectClassRoom
    restart: always
    volumes:
      - ../:/var/www/html/
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: client_host=host.docker.internal start_with_request=yes
  
 
  db:
    image: mysql:latest
    restart: always
    environment:
     - MYSQL_ALLOW_EMPTY_PASSWORD=true
      

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
  # phpmyadmin:
  #   image: phpmyadmin
  #   container_name: phpmyadmin
  #   restart: always
  #   ports:
  #     - 8080:80
    # depends_on:
    #   - mysql_db
    # links:
    #   - mysql_db
   

  # mysql_db: 
  #   image: mysql
  #   # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
  #   # (this is just an example, not intended to be a production configuration)
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: example

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"

# volumes:
#   db-data:

